version: "3"
services:
  buchling_frontend:
    build: ./frontend
    container_name: buchling_frontend
    restart: always
    ports:
    - 3014:80

  buchling_backend:
    build: ./backend
    container_name: buchling_backend
    restart: always
    ports:
    - 3013:8000
    depends_on:
      - buchling_database

  buchling_database:
    image: mongo
    container_name: buchling_database

